version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo_items
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  db-data:
